// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: qevents.proto

package eventspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventsService_GetTickEvents_FullMethodName      = "/qubic.events.EventsService/GetTickEvents"
	EventsService_GetStatus_FullMethodName          = "/qubic.events.EventsService/GetStatus"
	EventsService_GetTickProcessTime_FullMethodName = "/qubic.events.EventsService/GetTickProcessTime"
	EventsService_DecodeEvent_FullMethodName        = "/qubic.events.EventsService/DecodeEvent"
)

// EventsServiceClient is the client API for EventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventsServiceClient interface {
	GetTickEvents(ctx context.Context, in *GetTickEventsRequest, opts ...grpc.CallOption) (*TickEvents, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetTickProcessTime(ctx context.Context, in *GetTickProcessTimeRequest, opts ...grpc.CallOption) (*GetTickProcessTimeResponse, error)
	DecodeEvent(ctx context.Context, in *DecodeEventRequest, opts ...grpc.CallOption) (*DecodeEventResponse, error)
}

type eventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsServiceClient(cc grpc.ClientConnInterface) EventsServiceClient {
	return &eventsServiceClient{cc}
}

func (c *eventsServiceClient) GetTickEvents(ctx context.Context, in *GetTickEventsRequest, opts ...grpc.CallOption) (*TickEvents, error) {
	out := new(TickEvents)
	err := c.cc.Invoke(ctx, EventsService_GetTickEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, EventsService_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetTickProcessTime(ctx context.Context, in *GetTickProcessTimeRequest, opts ...grpc.CallOption) (*GetTickProcessTimeResponse, error) {
	out := new(GetTickProcessTimeResponse)
	err := c.cc.Invoke(ctx, EventsService_GetTickProcessTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) DecodeEvent(ctx context.Context, in *DecodeEventRequest, opts ...grpc.CallOption) (*DecodeEventResponse, error) {
	out := new(DecodeEventResponse)
	err := c.cc.Invoke(ctx, EventsService_DecodeEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServiceServer is the server API for EventsService service.
// All implementations must embed UnimplementedEventsServiceServer
// for forward compatibility
type EventsServiceServer interface {
	GetTickEvents(context.Context, *GetTickEventsRequest) (*TickEvents, error)
	GetStatus(context.Context, *emptypb.Empty) (*GetStatusResponse, error)
	GetTickProcessTime(context.Context, *GetTickProcessTimeRequest) (*GetTickProcessTimeResponse, error)
	DecodeEvent(context.Context, *DecodeEventRequest) (*DecodeEventResponse, error)
	mustEmbedUnimplementedEventsServiceServer()
}

// UnimplementedEventsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventsServiceServer struct {
}

func (UnimplementedEventsServiceServer) GetTickEvents(context.Context, *GetTickEventsRequest) (*TickEvents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTickEvents not implemented")
}
func (UnimplementedEventsServiceServer) GetStatus(context.Context, *emptypb.Empty) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEventsServiceServer) GetTickProcessTime(context.Context, *GetTickProcessTimeRequest) (*GetTickProcessTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTickProcessTime not implemented")
}
func (UnimplementedEventsServiceServer) DecodeEvent(context.Context, *DecodeEventRequest) (*DecodeEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeEvent not implemented")
}
func (UnimplementedEventsServiceServer) mustEmbedUnimplementedEventsServiceServer() {}

// UnsafeEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServiceServer will
// result in compilation errors.
type UnsafeEventsServiceServer interface {
	mustEmbedUnimplementedEventsServiceServer()
}

func RegisterEventsServiceServer(s grpc.ServiceRegistrar, srv EventsServiceServer) {
	s.RegisterService(&EventsService_ServiceDesc, srv)
}

func _EventsService_GetTickEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetTickEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetTickEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetTickEvents(ctx, req.(*GetTickEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetTickProcessTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickProcessTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetTickProcessTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetTickProcessTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetTickProcessTime(ctx, req.(*GetTickProcessTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_DecodeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).DecodeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_DecodeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).DecodeEvent(ctx, req.(*DecodeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsService_ServiceDesc is the grpc.ServiceDesc for EventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.events.EventsService",
	HandlerType: (*EventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTickEvents",
			Handler:    _EventsService_GetTickEvents_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _EventsService_GetStatus_Handler,
		},
		{
			MethodName: "GetTickProcessTime",
			Handler:    _EventsService_GetTickProcessTime_Handler,
		},
		{
			MethodName: "DecodeEvent",
			Handler:    _EventsService_DecodeEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qevents.proto",
}
