// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: qevents.proto

package eventspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Event_Header          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EventType     uint32                 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventSize     uint32                 `protobuf:"varint,3,opt,name=event_size,json=eventSize,proto3" json:"event_size,omitempty"`
	EventData     string                 `protobuf:"bytes,4,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_qevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetHeader() *Event_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Event) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetEventSize() uint32 {
	if x != nil {
		return x.EventSize
	}
	return 0
}

func (x *Event) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

type TransactionEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvents) Reset() {
	*x = TransactionEvents{}
	mi := &file_qevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvents) ProtoMessage() {}

func (x *TransactionEvents) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvents.ProtoReflect.Descriptor instead.
func (*TransactionEvents) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionEvents) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type TickEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	TxEvents      []*TransactionEvents   `protobuf:"bytes,2,rep,name=tx_events,json=txEvents,proto3" json:"tx_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickEvents) Reset() {
	*x = TickEvents{}
	mi := &file_qevents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickEvents) ProtoMessage() {}

func (x *TickEvents) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickEvents.ProtoReflect.Descriptor instead.
func (*TickEvents) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{2}
}

func (x *TickEvents) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickEvents) GetTxEvents() []*TransactionEvents {
	if x != nil {
		return x.TxEvents
	}
	return nil
}

type ProcessedTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickNumber    uint32                 `protobuf:"varint,1,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTick) Reset() {
	*x = ProcessedTick{}
	mi := &file_qevents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTick) ProtoMessage() {}

func (x *ProcessedTick) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTick.ProtoReflect.Descriptor instead.
func (*ProcessedTick) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessedTick) GetTickNumber() uint32 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

func (x *ProcessedTick) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type LastProcessedTick struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastProcessedTick uint32                 `protobuf:"varint,1,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LastProcessedTick) Reset() {
	*x = LastProcessedTick{}
	mi := &file_qevents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastProcessedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastProcessedTick) ProtoMessage() {}

func (x *LastProcessedTick) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastProcessedTick.ProtoReflect.Descriptor instead.
func (*LastProcessedTick) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{4}
}

func (x *LastProcessedTick) GetLastProcessedTick() uint32 {
	if x != nil {
		return x.LastProcessedTick
	}
	return 0
}

type NextAvailableTick struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextTickNumber uint32                 `protobuf:"varint,1,opt,name=next_tick_number,json=nextTickNumber,proto3" json:"next_tick_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NextAvailableTick) Reset() {
	*x = NextAvailableTick{}
	mi := &file_qevents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextAvailableTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextAvailableTick) ProtoMessage() {}

func (x *NextAvailableTick) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextAvailableTick.ProtoReflect.Descriptor instead.
func (*NextAvailableTick) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{5}
}

func (x *NextAvailableTick) GetNextTickNumber() uint32 {
	if x != nil {
		return x.NextTickNumber
	}
	return 0
}

type SkippedTicksInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTick     uint32                 `protobuf:"varint,1,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	EndTick       uint32                 `protobuf:"varint,2,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedTicksInterval) Reset() {
	*x = SkippedTicksInterval{}
	mi := &file_qevents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedTicksInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedTicksInterval) ProtoMessage() {}

func (x *SkippedTicksInterval) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedTicksInterval.ProtoReflect.Descriptor instead.
func (*SkippedTicksInterval) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{6}
}

func (x *SkippedTicksInterval) GetStartTick() uint32 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *SkippedTicksInterval) GetEndTick() uint32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

type SkippedTicksIntervalList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SkippedTicks  []*SkippedTicksInterval `protobuf:"bytes,1,rep,name=skipped_ticks,json=skippedTicks,proto3" json:"skipped_ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkippedTicksIntervalList) Reset() {
	*x = SkippedTicksIntervalList{}
	mi := &file_qevents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkippedTicksIntervalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkippedTicksIntervalList) ProtoMessage() {}

func (x *SkippedTicksIntervalList) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkippedTicksIntervalList.ProtoReflect.Descriptor instead.
func (*SkippedTicksIntervalList) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{7}
}

func (x *SkippedTicksIntervalList) GetSkippedTicks() []*SkippedTicksInterval {
	if x != nil {
		return x.SkippedTicks
	}
	return nil
}

type ProcessedTickInterval struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InitialProcessedTick uint32                 `protobuf:"varint,1,opt,name=initial_processed_tick,json=initialProcessedTick,proto3" json:"initial_processed_tick,omitempty"`
	LastProcessedTick    uint32                 `protobuf:"varint,2,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessedTickInterval) Reset() {
	*x = ProcessedTickInterval{}
	mi := &file_qevents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTickInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTickInterval) ProtoMessage() {}

func (x *ProcessedTickInterval) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTickInterval.ProtoReflect.Descriptor instead.
func (*ProcessedTickInterval) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessedTickInterval) GetInitialProcessedTick() uint32 {
	if x != nil {
		return x.InitialProcessedTick
	}
	return 0
}

func (x *ProcessedTickInterval) GetLastProcessedTick() uint32 {
	if x != nil {
		return x.LastProcessedTick
	}
	return 0
}

type ProcessedTickIntervalsPerEpoch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Epoch         uint32                   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Intervals     []*ProcessedTickInterval `protobuf:"bytes,2,rep,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedTickIntervalsPerEpoch) Reset() {
	*x = ProcessedTickIntervalsPerEpoch{}
	mi := &file_qevents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedTickIntervalsPerEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedTickIntervalsPerEpoch) ProtoMessage() {}

func (x *ProcessedTickIntervalsPerEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedTickIntervalsPerEpoch.ProtoReflect.Descriptor instead.
func (*ProcessedTickIntervalsPerEpoch) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessedTickIntervalsPerEpoch) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ProcessedTickIntervalsPerEpoch) GetIntervals() []*ProcessedTickInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

type DecodedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*DecodedEvent_QuTransferEvent_
	//	*DecodedEvent_AssetIssuanceEvent_
	//	*DecodedEvent_AssetOwnershipChangeEvent_
	//	*DecodedEvent_AssetPossessionChangeEvent_
	//	*DecodedEvent_BurnEvent_
	//	*DecodedEvent_DustBurnEvent_
	//	*DecodedEvent_SpectrumStatsEvent_
	//	*DecodedEvent_ContractMessageEvent_
	//	*DecodedEvent_ContractReserveDeductionEvent_
	//	*DecodedEvent_OracleQueryStatusChangeEvent_
	Event         isDecodedEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedEvent) Reset() {
	*x = DecodedEvent{}
	mi := &file_qevents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent) ProtoMessage() {}

func (x *DecodedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10}
}

func (x *DecodedEvent) GetEvent() isDecodedEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DecodedEvent) GetQuTransferEvent() *DecodedEvent_QuTransferEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_QuTransferEvent_); ok {
			return x.QuTransferEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetAssetIssuanceEvent() *DecodedEvent_AssetIssuanceEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_AssetIssuanceEvent_); ok {
			return x.AssetIssuanceEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetAssetOwnershipChangeEvent() *DecodedEvent_AssetOwnershipChangeEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_AssetOwnershipChangeEvent_); ok {
			return x.AssetOwnershipChangeEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetAssetPossessionChangeEvent() *DecodedEvent_AssetPossessionChangeEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_AssetPossessionChangeEvent_); ok {
			return x.AssetPossessionChangeEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetBurnEvent() *DecodedEvent_BurnEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_BurnEvent_); ok {
			return x.BurnEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetDustBurnEvent() *DecodedEvent_DustBurnEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_DustBurnEvent_); ok {
			return x.DustBurnEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetSpectrumStatsEvent() *DecodedEvent_SpectrumStatsEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_SpectrumStatsEvent_); ok {
			return x.SpectrumStatsEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetContractMessageEvent() *DecodedEvent_ContractMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_ContractMessageEvent_); ok {
			return x.ContractMessageEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetContractReserveDeductionEvent() *DecodedEvent_ContractReserveDeductionEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_ContractReserveDeductionEvent_); ok {
			return x.ContractReserveDeductionEvent
		}
	}
	return nil
}

func (x *DecodedEvent) GetOracleQueryStatusChangeEvent() *DecodedEvent_OracleQueryStatusChangeEvent {
	if x != nil {
		if x, ok := x.Event.(*DecodedEvent_OracleQueryStatusChangeEvent_); ok {
			return x.OracleQueryStatusChangeEvent
		}
	}
	return nil
}

type isDecodedEvent_Event interface {
	isDecodedEvent_Event()
}

type DecodedEvent_QuTransferEvent_ struct {
	QuTransferEvent *DecodedEvent_QuTransferEvent `protobuf:"bytes,1,opt,name=qu_transfer_event,json=quTransferEvent,proto3,oneof"`
}

type DecodedEvent_AssetIssuanceEvent_ struct {
	AssetIssuanceEvent *DecodedEvent_AssetIssuanceEvent `protobuf:"bytes,2,opt,name=asset_issuance_event,json=assetIssuanceEvent,proto3,oneof"`
}

type DecodedEvent_AssetOwnershipChangeEvent_ struct {
	AssetOwnershipChangeEvent *DecodedEvent_AssetOwnershipChangeEvent `protobuf:"bytes,3,opt,name=asset_ownership_change_event,json=assetOwnershipChangeEvent,proto3,oneof"`
}

type DecodedEvent_AssetPossessionChangeEvent_ struct {
	AssetPossessionChangeEvent *DecodedEvent_AssetPossessionChangeEvent `protobuf:"bytes,4,opt,name=asset_possession_change_event,json=assetPossessionChangeEvent,proto3,oneof"`
}

type DecodedEvent_BurnEvent_ struct {
	BurnEvent *DecodedEvent_BurnEvent `protobuf:"bytes,5,opt,name=burn_event,json=burnEvent,proto3,oneof"`
}

type DecodedEvent_DustBurnEvent_ struct {
	DustBurnEvent *DecodedEvent_DustBurnEvent `protobuf:"bytes,6,opt,name=dust_burn_event,json=dustBurnEvent,proto3,oneof"`
}

type DecodedEvent_SpectrumStatsEvent_ struct {
	SpectrumStatsEvent *DecodedEvent_SpectrumStatsEvent `protobuf:"bytes,7,opt,name=spectrum_stats_event,json=spectrumStatsEvent,proto3,oneof"`
}

type DecodedEvent_ContractMessageEvent_ struct {
	ContractMessageEvent *DecodedEvent_ContractMessageEvent `protobuf:"bytes,8,opt,name=contract_message_event,json=contractMessageEvent,proto3,oneof"`
}

type DecodedEvent_ContractReserveDeductionEvent_ struct {
	ContractReserveDeductionEvent *DecodedEvent_ContractReserveDeductionEvent `protobuf:"bytes,9,opt,name=contract_reserve_deduction_event,json=contractReserveDeductionEvent,proto3,oneof"`
}

type DecodedEvent_OracleQueryStatusChangeEvent_ struct {
	OracleQueryStatusChangeEvent *DecodedEvent_OracleQueryStatusChangeEvent `protobuf:"bytes,10,opt,name=oracle_query_status_change_event,json=oracleQueryStatusChangeEvent,proto3,oneof"`
}

func (*DecodedEvent_QuTransferEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_AssetIssuanceEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_AssetOwnershipChangeEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_AssetPossessionChangeEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_BurnEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_DustBurnEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_SpectrumStatsEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_ContractMessageEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_ContractReserveDeductionEvent_) isDecodedEvent_Event() {}

func (*DecodedEvent_OracleQueryStatusChangeEvent_) isDecodedEvent_Event() {}

type GetTickEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickEventsRequest) Reset() {
	*x = GetTickEventsRequest{}
	mi := &file_qevents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickEventsRequest) ProtoMessage() {}

func (x *GetTickEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickEventsRequest.ProtoReflect.Descriptor instead.
func (*GetTickEventsRequest) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{11}
}

func (x *GetTickEventsRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type GetTickProcessTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickProcessTimeRequest) Reset() {
	*x = GetTickProcessTimeRequest{}
	mi := &file_qevents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickProcessTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickProcessTimeRequest) ProtoMessage() {}

func (x *GetTickProcessTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickProcessTimeRequest.ProtoReflect.Descriptor instead.
func (*GetTickProcessTimeRequest) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{12}
}

func (x *GetTickProcessTimeRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type GetTickProcessTimeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProcessTimeSeconds uint64                 `protobuf:"varint,1,opt,name=process_time_seconds,json=processTimeSeconds,proto3" json:"process_time_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTickProcessTimeResponse) Reset() {
	*x = GetTickProcessTimeResponse{}
	mi := &file_qevents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickProcessTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickProcessTimeResponse) ProtoMessage() {}

func (x *GetTickProcessTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickProcessTimeResponse.ProtoReflect.Descriptor instead.
func (*GetTickProcessTimeResponse) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{13}
}

func (x *GetTickProcessTimeResponse) GetProcessTimeSeconds() uint64 {
	if x != nil {
		return x.ProcessTimeSeconds
	}
	return 0
}

type GetStatusResponse struct {
	state                          protoimpl.MessageState            `protogen:"open.v1"`
	LastProcessedTick              *ProcessedTick                    `protobuf:"bytes,1,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	LastProcessedTicksPerEpoch     map[uint32]uint32                 `protobuf:"bytes,2,rep,name=last_processed_ticks_per_epoch,json=lastProcessedTicksPerEpoch,proto3" json:"last_processed_ticks_per_epoch,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkippedTicks                   []*SkippedTicksInterval           `protobuf:"bytes,3,rep,name=skipped_ticks,json=skippedTicks,proto3" json:"skipped_ticks,omitempty"`
	ProcessedTickIntervalsPerEpoch []*ProcessedTickIntervalsPerEpoch `protobuf:"bytes,4,rep,name=processed_tick_intervals_per_epoch,json=processedTickIntervalsPerEpoch,proto3" json:"processed_tick_intervals_per_epoch,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_qevents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatusResponse) GetLastProcessedTick() *ProcessedTick {
	if x != nil {
		return x.LastProcessedTick
	}
	return nil
}

func (x *GetStatusResponse) GetLastProcessedTicksPerEpoch() map[uint32]uint32 {
	if x != nil {
		return x.LastProcessedTicksPerEpoch
	}
	return nil
}

func (x *GetStatusResponse) GetSkippedTicks() []*SkippedTicksInterval {
	if x != nil {
		return x.SkippedTicks
	}
	return nil
}

func (x *GetStatusResponse) GetProcessedTickIntervalsPerEpoch() []*ProcessedTickIntervalsPerEpoch {
	if x != nil {
		return x.ProcessedTickIntervalsPerEpoch
	}
	return nil
}

type DecodeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     uint32                 `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventData     string                 `protobuf:"bytes,2,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeEventRequest) Reset() {
	*x = DecodeEventRequest{}
	mi := &file_qevents_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeEventRequest) ProtoMessage() {}

func (x *DecodeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeEventRequest.ProtoReflect.Descriptor instead.
func (*DecodeEventRequest) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{15}
}

func (x *DecodeEventRequest) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *DecodeEventRequest) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

type DecodeEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecodedEvent  *DecodedEvent          `protobuf:"bytes,1,opt,name=decoded_event,json=decodedEvent,proto3" json:"decoded_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeEventResponse) Reset() {
	*x = DecodeEventResponse{}
	mi := &file_qevents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeEventResponse) ProtoMessage() {}

func (x *DecodeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeEventResponse.ProtoReflect.Descriptor instead.
func (*DecodeEventResponse) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{16}
}

func (x *DecodeEventResponse) GetDecodedEvent() *DecodedEvent {
	if x != nil {
		return x.DecodedEvent
	}
	return nil
}

type Event_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Tmp           uint32                 `protobuf:"varint,3,opt,name=tmp,proto3" json:"tmp,omitempty"`
	EventId       uint64                 `protobuf:"varint,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventDigest   uint64                 `protobuf:"varint,5,opt,name=event_digest,json=eventDigest,proto3" json:"event_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Header) Reset() {
	*x = Event_Header{}
	mi := &file_qevents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Header) ProtoMessage() {}

func (x *Event_Header) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Header.ProtoReflect.Descriptor instead.
func (*Event_Header) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_Header) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Event_Header) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Event_Header) GetTmp() uint32 {
	if x != nil {
		return x.Tmp
	}
	return 0
}

func (x *Event_Header) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event_Header) GetEventDigest() uint64 {
	if x != nil {
		return x.EventDigest
	}
	return 0
}

type DecodedEvent_QuTransferEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId        string                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedEvent_QuTransferEvent) Reset() {
	*x = DecodedEvent_QuTransferEvent{}
	mi := &file_qevents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_QuTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_QuTransferEvent) ProtoMessage() {}

func (x *DecodedEvent_QuTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_QuTransferEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_QuTransferEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DecodedEvent_QuTransferEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_QuTransferEvent) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *DecodedEvent_QuTransferEvent) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DecodedEvent_AssetIssuanceEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SourceId              string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	AssetName             string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	NumberOfDecimals      uint32                 `protobuf:"varint,3,opt,name=number_of_decimals,json=numberOfDecimals,proto3" json:"number_of_decimals,omitempty"`
	MeasurementUnit       []byte                 `protobuf:"bytes,4,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
	NumberOfShares        int64                  `protobuf:"varint,5,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	ManagingContractIndex int64                  `protobuf:"varint,6,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DecodedEvent_AssetIssuanceEvent) Reset() {
	*x = DecodedEvent_AssetIssuanceEvent{}
	mi := &file_qevents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_AssetIssuanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_AssetIssuanceEvent) ProtoMessage() {}

func (x *DecodedEvent_AssetIssuanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_AssetIssuanceEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_AssetIssuanceEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 1}
}

func (x *DecodedEvent_AssetIssuanceEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_AssetIssuanceEvent) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *DecodedEvent_AssetIssuanceEvent) GetNumberOfDecimals() uint32 {
	if x != nil {
		return x.NumberOfDecimals
	}
	return 0
}

func (x *DecodedEvent_AssetIssuanceEvent) GetMeasurementUnit() []byte {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

func (x *DecodedEvent_AssetIssuanceEvent) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

func (x *DecodedEvent_AssetIssuanceEvent) GetManagingContractIndex() int64 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

type DecodedEvent_AssetOwnershipChangeEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SourceId              string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId                string                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	IssuerId              string                 `protobuf:"bytes,3,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	AssetName             string                 `protobuf:"bytes,4,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	NumberOfDecimals      uint32                 `protobuf:"varint,5,opt,name=number_of_decimals,json=numberOfDecimals,proto3" json:"number_of_decimals,omitempty"`
	MeasurementUnit       []byte                 `protobuf:"bytes,6,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
	NumberOfShares        int64                  `protobuf:"varint,7,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	ManagingContractIndex int64                  `protobuf:"varint,8,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) Reset() {
	*x = DecodedEvent_AssetOwnershipChangeEvent{}
	mi := &file_qevents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_AssetOwnershipChangeEvent) ProtoMessage() {}

func (x *DecodedEvent_AssetOwnershipChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_AssetOwnershipChangeEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_AssetOwnershipChangeEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 2}
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetNumberOfDecimals() uint32 {
	if x != nil {
		return x.NumberOfDecimals
	}
	return 0
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetMeasurementUnit() []byte {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

func (x *DecodedEvent_AssetOwnershipChangeEvent) GetManagingContractIndex() int64 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

type DecodedEvent_AssetPossessionChangeEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SourceId              string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId                string                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	IssuerId              string                 `protobuf:"bytes,3,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	AssetName             string                 `protobuf:"bytes,4,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	NumberOfDecimals      uint32                 `protobuf:"varint,5,opt,name=number_of_decimals,json=numberOfDecimals,proto3" json:"number_of_decimals,omitempty"`
	MeasurementUnit       []byte                 `protobuf:"bytes,6,opt,name=measurement_unit,json=measurementUnit,proto3" json:"measurement_unit,omitempty"`
	NumberOfShares        int64                  `protobuf:"varint,7,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	ManagingContractIndex int64                  `protobuf:"varint,8,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DecodedEvent_AssetPossessionChangeEvent) Reset() {
	*x = DecodedEvent_AssetPossessionChangeEvent{}
	mi := &file_qevents_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_AssetPossessionChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_AssetPossessionChangeEvent) ProtoMessage() {}

func (x *DecodedEvent_AssetPossessionChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_AssetPossessionChangeEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_AssetPossessionChangeEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 3}
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetNumberOfDecimals() uint32 {
	if x != nil {
		return x.NumberOfDecimals
	}
	return 0
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetMeasurementUnit() []byte {
	if x != nil {
		return x.MeasurementUnit
	}
	return nil
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

func (x *DecodedEvent_AssetPossessionChangeEvent) GetManagingContractIndex() int64 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

type DecodedEvent_BurnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedEvent_BurnEvent) Reset() {
	*x = DecodedEvent_BurnEvent{}
	mi := &file_qevents_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_BurnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_BurnEvent) ProtoMessage() {}

func (x *DecodedEvent_BurnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_BurnEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_BurnEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 4}
}

func (x *DecodedEvent_BurnEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_BurnEvent) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DecodedEvent_DustBurnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfBurns uint32                 `protobuf:"varint,1,opt,name=number_of_burns,json=numberOfBurns,proto3" json:"number_of_burns,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedEvent_DustBurnEvent) Reset() {
	*x = DecodedEvent_DustBurnEvent{}
	mi := &file_qevents_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_DustBurnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_DustBurnEvent) ProtoMessage() {}

func (x *DecodedEvent_DustBurnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_DustBurnEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_DustBurnEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 5}
}

func (x *DecodedEvent_DustBurnEvent) GetNumberOfBurns() uint32 {
	if x != nil {
		return x.NumberOfBurns
	}
	return 0
}

func (x *DecodedEvent_DustBurnEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecodedEvent_DustBurnEvent) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DecodedEvent_SpectrumStatsEvent struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount               uint64                 `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DustThresholdBurnAll      uint64                 `protobuf:"varint,2,opt,name=dust_threshold_burn_all,json=dustThresholdBurnAll,proto3" json:"dust_threshold_burn_all,omitempty"`
	DustThresholdBurnHalf     uint64                 `protobuf:"varint,3,opt,name=dust_threshold_burn_half,json=dustThresholdBurnHalf,proto3" json:"dust_threshold_burn_half,omitempty"`
	NumberOfEntities          uint32                 `protobuf:"varint,4,opt,name=number_of_entities,json=numberOfEntities,proto3" json:"number_of_entities,omitempty"`
	EntityCategoryPopulations []uint32               `protobuf:"varint,5,rep,packed,name=entity_category_populations,json=entityCategoryPopulations,proto3" json:"entity_category_populations,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DecodedEvent_SpectrumStatsEvent) Reset() {
	*x = DecodedEvent_SpectrumStatsEvent{}
	mi := &file_qevents_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_SpectrumStatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_SpectrumStatsEvent) ProtoMessage() {}

func (x *DecodedEvent_SpectrumStatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_SpectrumStatsEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_SpectrumStatsEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 6}
}

func (x *DecodedEvent_SpectrumStatsEvent) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DecodedEvent_SpectrumStatsEvent) GetDustThresholdBurnAll() uint64 {
	if x != nil {
		return x.DustThresholdBurnAll
	}
	return 0
}

func (x *DecodedEvent_SpectrumStatsEvent) GetDustThresholdBurnHalf() uint64 {
	if x != nil {
		return x.DustThresholdBurnHalf
	}
	return 0
}

func (x *DecodedEvent_SpectrumStatsEvent) GetNumberOfEntities() uint32 {
	if x != nil {
		return x.NumberOfEntities
	}
	return 0
}

func (x *DecodedEvent_SpectrumStatsEvent) GetEntityCategoryPopulations() []uint32 {
	if x != nil {
		return x.EntityCategoryPopulations
	}
	return nil
}

type DecodedEvent_ContractMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    uint32                 `protobuf:"varint,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedEvent_ContractMessageEvent) Reset() {
	*x = DecodedEvent_ContractMessageEvent{}
	mi := &file_qevents_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_ContractMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_ContractMessageEvent) ProtoMessage() {}

func (x *DecodedEvent_ContractMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_ContractMessageEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_ContractMessageEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 7}
}

func (x *DecodedEvent_ContractMessageEvent) GetContractId() uint32 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *DecodedEvent_ContractMessageEvent) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type DecodedEvent_ContractReserveDeductionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeductedAmount  uint64                 `protobuf:"varint,1,opt,name=deducted_amount,json=deductedAmount,proto3" json:"deducted_amount,omitempty"`
	RemainingAmount int64                  `protobuf:"varint,2,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	ContractIndex   uint32                 `protobuf:"varint,3,opt,name=contract_index,json=contractIndex,proto3" json:"contract_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecodedEvent_ContractReserveDeductionEvent) Reset() {
	*x = DecodedEvent_ContractReserveDeductionEvent{}
	mi := &file_qevents_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_ContractReserveDeductionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_ContractReserveDeductionEvent) ProtoMessage() {}

func (x *DecodedEvent_ContractReserveDeductionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_ContractReserveDeductionEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_ContractReserveDeductionEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 8}
}

func (x *DecodedEvent_ContractReserveDeductionEvent) GetDeductedAmount() uint64 {
	if x != nil {
		return x.DeductedAmount
	}
	return 0
}

func (x *DecodedEvent_ContractReserveDeductionEvent) GetRemainingAmount() int64 {
	if x != nil {
		return x.RemainingAmount
	}
	return 0
}

func (x *DecodedEvent_ContractReserveDeductionEvent) GetContractIndex() uint32 {
	if x != nil {
		return x.ContractIndex
	}
	return 0
}

type DecodedEvent_OracleQueryStatusChangeEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueryingEntityId string                 `protobuf:"bytes,1,opt,name=querying_entity_id,json=queryingEntityId,proto3" json:"querying_entity_id,omitempty"`
	QueryId          int64                  `protobuf:"varint,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	InterfaceIndex   uint32                 `protobuf:"varint,3,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`
	Type             uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status           uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) Reset() {
	*x = DecodedEvent_OracleQueryStatusChangeEvent{}
	mi := &file_qevents_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedEvent_OracleQueryStatusChangeEvent) ProtoMessage() {}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_qevents_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedEvent_OracleQueryStatusChangeEvent.ProtoReflect.Descriptor instead.
func (*DecodedEvent_OracleQueryStatusChangeEvent) Descriptor() ([]byte, []int) {
	return file_qevents_proto_rawDescGZIP(), []int{10, 9}
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) GetQueryingEntityId() string {
	if x != nil {
		return x.QueryingEntityId
	}
	return ""
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) GetInterfaceIndex() uint32 {
	if x != nil {
		return x.InterfaceIndex
	}
	return 0
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DecodedEvent_OracleQueryStatusChangeEvent) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_qevents_proto protoreflect.FileDescriptor

const file_qevents_proto_rawDesc = "" +
	"\n" +
	"\rqevents.proto\x12\fqubic.events\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9d\x02\n" +
	"\x05Event\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.qubic.events.Event.HeaderR\x06header\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\rR\teventType\x12\x1d\n" +
	"\n" +
	"event_size\x18\x03 \x01(\rR\teventSize\x12\x1d\n" +
	"\n" +
	"event_data\x18\x04 \x01(\tR\teventData\x1a\x82\x01\n" +
	"\x06Header\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12\x10\n" +
	"\x03tmp\x18\x03 \x01(\rR\x03tmp\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\x04R\aeventId\x12!\n" +
	"\fevent_digest\x18\x05 \x01(\x04R\veventDigest\"U\n" +
	"\x11TransactionEvents\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12+\n" +
	"\x06events\x18\x02 \x03(\v2\x13.qubic.events.EventR\x06events\"^\n" +
	"\n" +
	"TickEvents\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12<\n" +
	"\ttx_events\x18\x02 \x03(\v2\x1f.qubic.events.TransactionEventsR\btxEvents\"F\n" +
	"\rProcessedTick\x12\x1f\n" +
	"\vtick_number\x18\x01 \x01(\rR\n" +
	"tickNumber\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\"C\n" +
	"\x11LastProcessedTick\x12.\n" +
	"\x13last_processed_tick\x18\x01 \x01(\rR\x11lastProcessedTick\"=\n" +
	"\x11NextAvailableTick\x12(\n" +
	"\x10next_tick_number\x18\x01 \x01(\rR\x0enextTickNumber\"P\n" +
	"\x14SkippedTicksInterval\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x01 \x01(\rR\tstartTick\x12\x19\n" +
	"\bend_tick\x18\x02 \x01(\rR\aendTick\"c\n" +
	"\x18SkippedTicksIntervalList\x12G\n" +
	"\rskipped_ticks\x18\x01 \x03(\v2\".qubic.events.SkippedTicksIntervalR\fskippedTicks\"}\n" +
	"\x15ProcessedTickInterval\x124\n" +
	"\x16initial_processed_tick\x18\x01 \x01(\rR\x14initialProcessedTick\x12.\n" +
	"\x13last_processed_tick\x18\x02 \x01(\rR\x11lastProcessedTick\"y\n" +
	"\x1eProcessedTickIntervalsPerEpoch\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12A\n" +
	"\tintervals\x18\x02 \x03(\v2#.qubic.events.ProcessedTickIntervalR\tintervals\"\xb7\x17\n" +
	"\fDecodedEvent\x12X\n" +
	"\x11qu_transfer_event\x18\x01 \x01(\v2*.qubic.events.DecodedEvent.QuTransferEventH\x00R\x0fquTransferEvent\x12a\n" +
	"\x14asset_issuance_event\x18\x02 \x01(\v2-.qubic.events.DecodedEvent.AssetIssuanceEventH\x00R\x12assetIssuanceEvent\x12w\n" +
	"\x1casset_ownership_change_event\x18\x03 \x01(\v24.qubic.events.DecodedEvent.AssetOwnershipChangeEventH\x00R\x19assetOwnershipChangeEvent\x12z\n" +
	"\x1dasset_possession_change_event\x18\x04 \x01(\v25.qubic.events.DecodedEvent.AssetPossessionChangeEventH\x00R\x1aassetPossessionChangeEvent\x12E\n" +
	"\n" +
	"burn_event\x18\x05 \x01(\v2$.qubic.events.DecodedEvent.BurnEventH\x00R\tburnEvent\x12R\n" +
	"\x0fdust_burn_event\x18\x06 \x01(\v2(.qubic.events.DecodedEvent.DustBurnEventH\x00R\rdustBurnEvent\x12a\n" +
	"\x14spectrum_stats_event\x18\a \x01(\v2-.qubic.events.DecodedEvent.SpectrumStatsEventH\x00R\x12spectrumStatsEvent\x12g\n" +
	"\x16contract_message_event\x18\b \x01(\v2/.qubic.events.DecodedEvent.ContractMessageEventH\x00R\x14contractMessageEvent\x12\x83\x01\n" +
	" contract_reserve_deduction_event\x18\t \x01(\v28.qubic.events.DecodedEvent.ContractReserveDeductionEventH\x00R\x1dcontractReserveDeductionEvent\x12\x81\x01\n" +
	" oracle_query_status_change_event\x18\n" +
	" \x01(\v27.qubic.events.DecodedEvent.OracleQueryStatusChangeEventH\x00R\x1coracleQueryStatusChangeEvent\x1a_\n" +
	"\x0fQuTransferEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\tR\x06destId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x1a\x8b\x02\n" +
	"\x12AssetIssuanceEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12,\n" +
	"\x12number_of_decimals\x18\x03 \x01(\rR\x10numberOfDecimals\x12)\n" +
	"\x10measurement_unit\x18\x04 \x01(\fR\x0fmeasurementUnit\x12(\n" +
	"\x10number_of_shares\x18\x05 \x01(\x03R\x0enumberOfShares\x126\n" +
	"\x17managing_contract_index\x18\x06 \x01(\x03R\x15managingContractIndex\x1a\xc8\x02\n" +
	"\x19AssetOwnershipChangeEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\tR\x06destId\x12\x1b\n" +
	"\tissuer_id\x18\x03 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x04 \x01(\tR\tassetName\x12,\n" +
	"\x12number_of_decimals\x18\x05 \x01(\rR\x10numberOfDecimals\x12)\n" +
	"\x10measurement_unit\x18\x06 \x01(\fR\x0fmeasurementUnit\x12(\n" +
	"\x10number_of_shares\x18\a \x01(\x03R\x0enumberOfShares\x126\n" +
	"\x17managing_contract_index\x18\b \x01(\x03R\x15managingContractIndex\x1a\xc9\x02\n" +
	"\x1aAssetPossessionChangeEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\tR\x06destId\x12\x1b\n" +
	"\tissuer_id\x18\x03 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x04 \x01(\tR\tassetName\x12,\n" +
	"\x12number_of_decimals\x18\x05 \x01(\rR\x10numberOfDecimals\x12)\n" +
	"\x10measurement_unit\x18\x06 \x01(\fR\x0fmeasurementUnit\x12(\n" +
	"\x10number_of_shares\x18\a \x01(\x03R\x0enumberOfShares\x126\n" +
	"\x17managing_contract_index\x18\b \x01(\x03R\x15managingContractIndex\x1a@\n" +
	"\tBurnEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x1al\n" +
	"\rDustBurnEvent\x12&\n" +
	"\x0fnumber_of_burns\x18\x01 \x01(\rR\rnumberOfBurns\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x1a\x95\x02\n" +
	"\x12SpectrumStatsEvent\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x04R\vtotalAmount\x125\n" +
	"\x17dust_threshold_burn_all\x18\x02 \x01(\x04R\x14dustThresholdBurnAll\x127\n" +
	"\x18dust_threshold_burn_half\x18\x03 \x01(\x04R\x15dustThresholdBurnHalf\x12,\n" +
	"\x12number_of_entities\x18\x04 \x01(\rR\x10numberOfEntities\x12>\n" +
	"\x1bentity_category_populations\x18\x05 \x03(\rR\x19entityCategoryPopulations\x1aQ\n" +
	"\x14ContractMessageEvent\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\rR\n" +
	"contractId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x1a\x9a\x01\n" +
	"\x1dContractReserveDeductionEvent\x12'\n" +
	"\x0fdeducted_amount\x18\x01 \x01(\x04R\x0edeductedAmount\x12)\n" +
	"\x10remaining_amount\x18\x02 \x01(\x03R\x0fremainingAmount\x12%\n" +
	"\x0econtract_index\x18\x03 \x01(\rR\rcontractIndex\x1a\xbc\x01\n" +
	"\x1cOracleQueryStatusChangeEvent\x12,\n" +
	"\x12querying_entity_id\x18\x01 \x01(\tR\x10queryingEntityId\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\x03R\aqueryId\x12'\n" +
	"\x0finterface_index\x18\x03 \x01(\rR\x0einterfaceIndex\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06statusB\a\n" +
	"\x05event\"*\n" +
	"\x14GetTickEventsRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"/\n" +
	"\x19GetTickProcessTimeRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"N\n" +
	"\x1aGetTickProcessTimeResponse\x120\n" +
	"\x14process_time_seconds\x18\x01 \x01(\x04R\x12processTimeSeconds\"\xf8\x03\n" +
	"\x11GetStatusResponse\x12K\n" +
	"\x13last_processed_tick\x18\x01 \x01(\v2\x1b.qubic.events.ProcessedTickR\x11lastProcessedTick\x12\x83\x01\n" +
	"\x1elast_processed_ticks_per_epoch\x18\x02 \x03(\v2?.qubic.events.GetStatusResponse.LastProcessedTicksPerEpochEntryR\x1alastProcessedTicksPerEpoch\x12G\n" +
	"\rskipped_ticks\x18\x03 \x03(\v2\".qubic.events.SkippedTicksIntervalR\fskippedTicks\x12x\n" +
	"\"processed_tick_intervals_per_epoch\x18\x04 \x03(\v2,.qubic.events.ProcessedTickIntervalsPerEpochR\x1eprocessedTickIntervalsPerEpoch\x1aM\n" +
	"\x1fLastProcessedTicksPerEpochEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"R\n" +
	"\x12DecodeEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\rR\teventType\x12\x1d\n" +
	"\n" +
	"event_data\x18\x02 \x01(\tR\teventData\"V\n" +
	"\x13DecodeEventResponse\x12?\n" +
	"\rdecoded_event\x18\x01 \x01(\v2\x1a.qubic.events.DecodedEventR\fdecodedEvent2\xef\x03\n" +
	"\rEventsService\x12r\n" +
	"\rGetTickEvents\x12\".qubic.events.GetTickEventsRequest\x1a\x18.qubic.events.TickEvents\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/events/getTickEvents\x12_\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1f.qubic.events.GetStatusResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/events/status\x12\x91\x01\n" +
	"\x12GetTickProcessTime\x12'.qubic.events.GetTickProcessTimeRequest\x1a(.qubic.events.GetTickProcessTimeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/events/getTickProcessTime\x12u\n" +
	"\vDecodeEvent\x12 .qubic.events.DecodeEventRequest\x1a!.qubic.events.DecodeEventResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/events/decodeEventB%Z#github.com/qubic/go-events/eventspbb\x06proto3"

var (
	file_qevents_proto_rawDescOnce sync.Once
	file_qevents_proto_rawDescData []byte
)

func file_qevents_proto_rawDescGZIP() []byte {
	file_qevents_proto_rawDescOnce.Do(func() {
		file_qevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qevents_proto_rawDesc), len(file_qevents_proto_rawDesc)))
	})
	return file_qevents_proto_rawDescData
}

var file_qevents_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_qevents_proto_goTypes = []any{
	(*Event)(nil),                                      // 0: qubic.events.Event
	(*TransactionEvents)(nil),                          // 1: qubic.events.TransactionEvents
	(*TickEvents)(nil),                                 // 2: qubic.events.TickEvents
	(*ProcessedTick)(nil),                              // 3: qubic.events.ProcessedTick
	(*LastProcessedTick)(nil),                          // 4: qubic.events.LastProcessedTick
	(*NextAvailableTick)(nil),                          // 5: qubic.events.NextAvailableTick
	(*SkippedTicksInterval)(nil),                       // 6: qubic.events.SkippedTicksInterval
	(*SkippedTicksIntervalList)(nil),                   // 7: qubic.events.SkippedTicksIntervalList
	(*ProcessedTickInterval)(nil),                      // 8: qubic.events.ProcessedTickInterval
	(*ProcessedTickIntervalsPerEpoch)(nil),             // 9: qubic.events.ProcessedTickIntervalsPerEpoch
	(*DecodedEvent)(nil),                               // 10: qubic.events.DecodedEvent
	(*GetTickEventsRequest)(nil),                       // 11: qubic.events.GetTickEventsRequest
	(*GetTickProcessTimeRequest)(nil),                  // 12: qubic.events.GetTickProcessTimeRequest
	(*GetTickProcessTimeResponse)(nil),                 // 13: qubic.events.GetTickProcessTimeResponse
	(*GetStatusResponse)(nil),                          // 14: qubic.events.GetStatusResponse
	(*DecodeEventRequest)(nil),                         // 15: qubic.events.DecodeEventRequest
	(*DecodeEventResponse)(nil),                        // 16: qubic.events.DecodeEventResponse
	(*Event_Header)(nil),                               // 17: qubic.events.Event.Header
	(*DecodedEvent_QuTransferEvent)(nil),               // 18: qubic.events.DecodedEvent.QuTransferEvent
	(*DecodedEvent_AssetIssuanceEvent)(nil),            // 19: qubic.events.DecodedEvent.AssetIssuanceEvent
	(*DecodedEvent_AssetOwnershipChangeEvent)(nil),     // 20: qubic.events.DecodedEvent.AssetOwnershipChangeEvent
	(*DecodedEvent_AssetPossessionChangeEvent)(nil),    // 21: qubic.events.DecodedEvent.AssetPossessionChangeEvent
	(*DecodedEvent_BurnEvent)(nil),                     // 22: qubic.events.DecodedEvent.BurnEvent
	(*DecodedEvent_DustBurnEvent)(nil),                 // 23: qubic.events.DecodedEvent.DustBurnEvent
	(*DecodedEvent_SpectrumStatsEvent)(nil),            // 24: qubic.events.DecodedEvent.SpectrumStatsEvent
	(*DecodedEvent_ContractMessageEvent)(nil),          // 25: qubic.events.DecodedEvent.ContractMessageEvent
	(*DecodedEvent_ContractReserveDeductionEvent)(nil), // 26: qubic.events.DecodedEvent.ContractReserveDeductionEvent
	(*DecodedEvent_OracleQueryStatusChangeEvent)(nil),  // 27: qubic.events.DecodedEvent.OracleQueryStatusChangeEvent
	nil,                   // 28: qubic.events.GetStatusResponse.LastProcessedTicksPerEpochEntry
	(*emptypb.Empty)(nil), // 29: google.protobuf.Empty
}
var file_qevents_proto_depIdxs = []int32{
	17, // 0: qubic.events.Event.header:type_name -> qubic.events.Event.Header
	0,  // 1: qubic.events.TransactionEvents.events:type_name -> qubic.events.Event
	1,  // 2: qubic.events.TickEvents.tx_events:type_name -> qubic.events.TransactionEvents
	6,  // 3: qubic.events.SkippedTicksIntervalList.skipped_ticks:type_name -> qubic.events.SkippedTicksInterval
	8,  // 4: qubic.events.ProcessedTickIntervalsPerEpoch.intervals:type_name -> qubic.events.ProcessedTickInterval
	18, // 5: qubic.events.DecodedEvent.qu_transfer_event:type_name -> qubic.events.DecodedEvent.QuTransferEvent
	19, // 6: qubic.events.DecodedEvent.asset_issuance_event:type_name -> qubic.events.DecodedEvent.AssetIssuanceEvent
	20, // 7: qubic.events.DecodedEvent.asset_ownership_change_event:type_name -> qubic.events.DecodedEvent.AssetOwnershipChangeEvent
	21, // 8: qubic.events.DecodedEvent.asset_possession_change_event:type_name -> qubic.events.DecodedEvent.AssetPossessionChangeEvent
	22, // 9: qubic.events.DecodedEvent.burn_event:type_name -> qubic.events.DecodedEvent.BurnEvent
	23, // 10: qubic.events.DecodedEvent.dust_burn_event:type_name -> qubic.events.DecodedEvent.DustBurnEvent
	24, // 11: qubic.events.DecodedEvent.spectrum_stats_event:type_name -> qubic.events.DecodedEvent.SpectrumStatsEvent
	25, // 12: qubic.events.DecodedEvent.contract_message_event:type_name -> qubic.events.DecodedEvent.ContractMessageEvent
	26, // 13: qubic.events.DecodedEvent.contract_reserve_deduction_event:type_name -> qubic.events.DecodedEvent.ContractReserveDeductionEvent
	27, // 14: qubic.events.DecodedEvent.oracle_query_status_change_event:type_name -> qubic.events.DecodedEvent.OracleQueryStatusChangeEvent
	3,  // 15: qubic.events.GetStatusResponse.last_processed_tick:type_name -> qubic.events.ProcessedTick
	28, // 16: qubic.events.GetStatusResponse.last_processed_ticks_per_epoch:type_name -> qubic.events.GetStatusResponse.LastProcessedTicksPerEpochEntry
	6,  // 17: qubic.events.GetStatusResponse.skipped_ticks:type_name -> qubic.events.SkippedTicksInterval
	9,  // 18: qubic.events.GetStatusResponse.processed_tick_intervals_per_epoch:type_name -> qubic.events.ProcessedTickIntervalsPerEpoch
	10, // 19: qubic.events.DecodeEventResponse.decoded_event:type_name -> qubic.events.DecodedEvent
	11, // 20: qubic.events.EventsService.GetTickEvents:input_type -> qubic.events.GetTickEventsRequest
	29, // 21: qubic.events.EventsService.GetStatus:input_type -> google.protobuf.Empty
	12, // 22: qubic.events.EventsService.GetTickProcessTime:input_type -> qubic.events.GetTickProcessTimeRequest
	15, // 23: qubic.events.EventsService.DecodeEvent:input_type -> qubic.events.DecodeEventRequest
	2,  // 24: qubic.events.EventsService.GetTickEvents:output_type -> qubic.events.TickEvents
	14, // 25: qubic.events.EventsService.GetStatus:output_type -> qubic.events.GetStatusResponse
	13, // 26: qubic.events.EventsService.GetTickProcessTime:output_type -> qubic.events.GetTickProcessTimeResponse
	16, // 27: qubic.events.EventsService.DecodeEvent:output_type -> qubic.events.DecodeEventResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_qevents_proto_init() }
func file_qevents_proto_init() {
	if File_qevents_proto != nil {
		return
	}
	file_qevents_proto_msgTypes[10].OneofWrappers = []any{
		(*DecodedEvent_QuTransferEvent_)(nil),
		(*DecodedEvent_AssetIssuanceEvent_)(nil),
		(*DecodedEvent_AssetOwnershipChangeEvent_)(nil),
		(*DecodedEvent_AssetPossessionChangeEvent_)(nil),
		(*DecodedEvent_BurnEvent_)(nil),
		(*DecodedEvent_DustBurnEvent_)(nil),
		(*DecodedEvent_SpectrumStatsEvent_)(nil),
		(*DecodedEvent_ContractMessageEvent_)(nil),
		(*DecodedEvent_ContractReserveDeductionEvent_)(nil),
		(*DecodedEvent_OracleQueryStatusChangeEvent_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qevents_proto_rawDesc), len(file_qevents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qevents_proto_goTypes,
		DependencyIndexes: file_qevents_proto_depIdxs,
		MessageInfos:      file_qevents_proto_msgTypes,
	}.Build()
	File_qevents_proto = out.File
	file_qevents_proto_goTypes = nil
	file_qevents_proto_depIdxs = nil
}
